version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
      time: "05:25"
      timezone: Europe/Zurich

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "05:25"
      timezone: Europe/Zurich
